# Generated by Django 5.2.15 on 2026-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
