# Generated by Django 5.2.15 on 2026-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='regiao',
            field=models.CharField(max_length=150, verbose_name='região'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('sob_encomenda', 'Sob encomenda')], default='disponivel', max_length=20),
        ),
    ]
