# Generated by Django 5.2.15 on 2026-06-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
