# Generated by Django 5.2.15 on 2026-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_conta',
            field=models.CharField(choices=[('produtor', 'Produtor rural'), ('comprador', 'Comprador')], default='comprador', max_length=20),
        ),
    ]
