# Generated by Django 5.2.15 on 2026-06-06 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProdutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('tipo_producao', models.CharField(help_text='Ex: hortaliças, frutas, leite, grãos, orgânicos etc.', max_length=150)),
                ('capacidade_producao', models.CharField(blank=True, help_text='Ex: 500 kg por semana, 2 toneladas por mês etc.', max_length=150)),
                ('contato_comercial', models.CharField(blank=True, max_length=100)),
                ('exibir_contato', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtores/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_produtor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do produtor',
                'verbose_name_plural': 'Perfis dos produtores',
            },
        ),
    ]
